using BookStoreAbpSolution.EntityFrameworkCore;
using Xunit;

namespace BookStoreAbpSolution.EntityFrameworkCore;

public class BookStoreAbpSolutionEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<BookStoreAbpSolutionEntityFrameworkCoreFixture>
{

}
